import { create } from 'zustand';

// ─────────────────────────────────────────────────────────────────────────────
// useToastStore — Zustand store for transient toast notifications
//
// Features:
//   • Max 3 visible toasts (oldest is evicted when cap is reached)
//   • Each toast auto-dismisses after `duration` ms (default: 4 000 ms)
//   • Toasts can be manually dismissed via removeToast(id)
//
// Usage:
//   import { useToastStore } from '@/store/useToastStore';
//   const addToast = useToastStore((s) => s.addToast);
//   addToast({ message: 'Saved!', variant: 'success' });
// ─────────────────────────────────────────────────────────────────────────────

export type ToastVariant = 'success' | 'error' | 'warning' | 'info';

export interface Toast {
  /** Unique identifier — auto-generated by addToast */
  id: string;
  /** The human-readable message displayed in the toast */
  message: string;
  /** Visual/semantic variant */
  variant: ToastVariant;
  /** Auto-dismiss delay in milliseconds (default: 4 000) */
  duration: number;
}

// Omit auto-generated fields from the public addToast payload
export type AddToastPayload = Omit<Toast, 'id'> & { duration?: number };

interface ToastState {
  toasts: Toast[];
}

interface ToastActions {
  addToast:    (payload: AddToastPayload) => void;
  removeToast: (id: string) => void;
}

const MAX_TOASTS = 3;
const DEFAULT_DURATION = 4_000;

export const useToastStore = create<ToastState & ToastActions>((set, get) => ({
  toasts: [],

  addToast: (payload) => {
    const id = `toast-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;
    const duration = payload.duration ?? DEFAULT_DURATION;
    const toast: Toast = { ...payload, id, duration };

    set((state) => {
      // Evict oldest toasts to stay within MAX_TOASTS
      const next = [...state.toasts, toast];
      return { toasts: next.length > MAX_TOASTS ? next.slice(next.length - MAX_TOASTS) : next };
    });

    // Schedule auto-dismiss
    setTimeout(() => {
      get().removeToast(id);
    }, duration);
  },

  removeToast: (id) => {
    set((state) => ({
      toasts: state.toasts.filter((t) => t.id !== id),
    }));
  },
}));
